### ISSUE TITLE
Versons antigas da MarteX core

### ISSUE THREAD

**Issue by Jetro-Costa** [Jetro-Costa/MarteXCoin_Documentation_GitHub_format_and_wiki#3]
@marcianovc você tem todas as versões antigas da MarteX core para fazer uma boa documentação neste [link](https://github.com/Jetro-Costa/MarteXCoin_Documentation_GitHub_format_and_wiki/blob/atualizacao/wallets/recovery.rst).

Pela documentação da Dash, dá para se importar endereço muitos antigos (antes de um hard fork) e continuar usando-os.

Também dá para manipular endereço antes de um hard forck se a wallet estiver totalmente desconectada da internet e não tendo baixado nehuma parte da blockchain.

**Comment by marcianovc** [comment]
tem versões antigas da MXT que não são compatíveis com a atual...

**Comment by Jetro-Costa** [comment]
> tem versões antigas da MXT que não são compatíveis com a atual...

Sim, mas tem como as pessoas recuperarem os endereços antigos com a MarteX core antiga; fazer o backup dos endereços antigos ; colocar numa MarteX core atual (sem ter baixado nenhum arquivo da blockchain) e os endereços estarem disponíveis para uso normalmente?

**Comment by marcianovc** [comment]
> > tem versões antigas da MXT que não são compatíveis com a atual...
> 
> Sim, mas tem como as pessoas recuperarem os endereços antigos com a MarteX core antiga; fazer o backup dos endereços antigos ; colocar numa MarteX core atual (sem ter baixado nenhum arquivo da blockchain) e os endereços estarem disponíveis para uso normalmente?

Os endereços sim, ja os saldos não (da versão 2 para traz foi feito swap MANUAL)

**Comment by Jetro-Costa** [comment]
Obrigado pelas informações, colocarei isso na documentação.

Em qua, 13 de jan de 2021 07:22, Marciano Valverde da Costa <
notifications@github.com> escreveu:
